name: Docker

on:
  push:
    branches: [ "pretest","dev","test","acc","release","main","master","llinkiddemo" ]

env:
  DEPLOYMENT_REQUESTS_PROJECT: "jgeeliss-kov"
  DEPLOYMENT_REQUESTS_REPO: "tmp-github-migration-deployment-requests"
  SEND_EMAILS_TO: '["johannes.govaerts@katholiekonderwijs.vlaanderen", "frederik.tilkin@katholiekonderwijs.vlaanderen", "jesse.geelissen@katholiekonderwijs.vlaanderen"]'
  REPO_NAME: "${{ github.event.repository.name }}" 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: clone the deployment-requests repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEPLOYMENT_REQUESTS_PROJECT }}/${{ env.DEPLOYMENT_REQUESTS_REPO }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          # path: ./${{ env.DEPLOYMENT_REQUESTS_REPO }}

      - name: determine what to deploy
        run: |
          ### set some variables (REPO, COMMIT, ENV>) ###
          REPO_SPLIT=($(node -e "
            const configRepo = '${REPO_NAME}';
            const configRepoSplit = configRepo.split('.config.');
            console.log(configRepoSplit[0], configRepoSplit[1]);
          "))
          REPO="${REPO_SPLIT[0]}"
          echo "REPO=${REPO}" >> $GITHUB_ENV
          ENV="${REPO_SPLIT[1]}"

          ### translate env name to the corresponding branch ###
          BRANCH=$(node -e "
            const branchNameToEnvMap = {
              pretest: 'pretest',
              test: 'dev',
              acc: 'release',
              prod: 'master',
              llinkiddemo: 'llinkiddemo',
            };
            console.log(branchNameToEnvMap['${ENV}'] || '');
          ")
          echo "ENV=${ENV}" >> $GITHUB_ENV
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "We will try to deploy ${REPO} branch ${BRANCH} to the ${ENV} environment."
          ############################################################

          ### exit if ENV not set (if we are on a branch that should not be deployed) ###
          if [ "${ENV}" = "" ]; then
            echo "ENV not set, we assume this is a branch that should not be deployed automatically, exiting..."
          fi
          ############################################################

      - name: send deployment request to repo deployment-requests
        if: env.ENV != ''
        run: |
          ### request deployment (by adding a commit to deployment-requests repo) ###

          (
            ls
            git config user.email "${REPO}-bitbucket-pipeline@katholiekonderwijs.vlaanderen"
            git config user.name "${REPO}"
            git pull \
              && git commit --allow-empty -m "{ \"request\": \"DEPLOYMENT\", \"repo\": \"verlof\", \"env\": \"${ENV}\", \"commitHash\": \"${BRANCH}\", \"emailAddresses\": ${SEND_EMAILS_TO} }" \
              && git push
          )
          ############################################################